# modules/symbol_data_fetcher/symbol_data_fetcher_config.py

from pathlib import Path
from zoneinfo import ZoneInfo

# Muokattava aikavyöhyke — voidaan vaihtaa esim. ZoneInfo("UTC")
LOCAL_TIMEZONE = ZoneInfo("Europe/Helsinki")

# Top-N assettia long/short-suosituksiin
TOP_N_LONG = 20
TOP_N_SHORT = 20

# Kuinka vanhaa dataa pidetään vielä tuoreena (minuuteissa)
OHLCV_MAX_AGE_MINUTES = 180

# Painot eri aikajaksoille analyysissä
INTERVAL_WEIGHTS = {
    "1h": 1.0,
    "4h": 1.5,
    "1d": 2.0,
}

# INTERVALS
INTERVALS = ["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1w"]

# LOGS
OHLCV_LOG_PATH = Path("integrations/multi_interval_ohlcv/ohlcv_fetch_log.jsonl")
SYMBOL_LOG_PATH = Path("modules/symbol_data_fetcher/symbol_data_log.jsonl")

# SYMBOLS
MAIN_SYMBOLS = [
    "BTCUSDT", 
    "ETHUSDT", 
    "SOLUSDT", 
    "XRPUSDT", 
    "ADAUSDT", 
    "HYPEUSDT", 
    "SUIUSDT", 
    "LINKUSDT", 
    "XLMUSDT", 
    "LTCUSDT", 
    "HBARUSDT"
]
SUPPORTED_SYMBOLS = [
    "BTCUSDT", 
    "ETHUSDT", 
    "XRPUSDT", 
    "BCHUSDT", 
    "LTCUSDT", 
    "XTZUSDT", 
    "LINKUSDT", 
    "ADAUSDT", 
    "DOTUSDT", 
    "UNIUSDT", 
    "XEMUSDT", 
    "SUSHIUSDT", 
    "AAVEUSDT", 
    "DOGEUSDT", 
    "ETCUSDT", 
    "BNBUSDT", 
    "FILUSDT", 
    "SOLUSDT", 
    "XLMUSDT", 
    "TRXUSDT", 
    "VETUSDT", 
    "THETAUSDT", 
    "COMPUSDT", 
    "AXSUSDT", 
    "SANDUSDT", 
    "MANAUSDT", 
    "KSMUSDT", 
    "ATOMUSDT", 
    "AVAXUSDT", 
    "CHZUSDT", 
    "CRVUSDT", 
    "ENJUSDT", 
    "GRTUSDT", 
    # "SHIB1000USDT", -> not supported by exchanges 3.7.2025 
    "YFIUSDT", 
    # "BSVUSDT", -> not supported by exchanges 3.7.2025 
    "ICPUSDT", 
    "ALGOUSDT", 
    "DYDXUSDT", 
    "NEARUSDT", 
    "IOSTUSDT", 
    "DASHUSDT", 
    "GALAUSDT", 
    "CELRUSDT", 
    "HBARUSDT", 
    "ONEUSDT", 
    "C98USDT", 
    "AGLDUSDT", 
    "MKRUSDT", 
    "COTIUSDT", 
    "ALICEUSDT", 
    "EGLDUSDT", 
    "RUNEUSDT", 
    "ILVUSDT", 
    "FLOWUSDT", 
    "WOOUSDT", 
    "LRCUSDT", 
    "ENSUSDT", 
    "IOTXUSDT", 
    "CHRUSDT", 
    "BATUSDT", 
    "STORJUSDT", 
    "SNXUSDT", 
    "SLPUSDT", 
    "ANKRUSDT", 
    "LPTUSDT", 
    "QTUMUSDT", 
    "CROUSDT", 
    "SXPUSDT", 
    "YGGUSDT", 
    "ZECUSDT", 
    "IMXUSDT", 
    "SFPUSDT", 
    "AUDIOUSDT", 
    "ZENUSDT", 
    "SKLUSDT", 
    "CVCUSDT", 
    "RSRUSDT", 
    "STXUSDT", 
    "MASKUSDT", 
    "CTKUSDT", 
    "REQUSDT", 
    "1INCHUSDT", 
    "SPELLUSDT", 
    "ARUSDT", 
    "XMRUSDT", 
    "PEOPLEUSDT", 
    "IOTAUSDT", 
    "ICXUSDT", 
    "CELOUSDT", 
    "WAVESUSDT", 
    "RVNUSDT", 
    "KNCUSDT", 
    "KAVAUSDT", 
    "ROSEUSDT", 
    "JASMYUSDT", 
    "QNTUSDT", 
    "ZILUSDT", 
    "NEOUSDT", 
    "CKBUSDT", 
    "SUNUSDT", 
    "JSTUSDT", 
    "BANDUSDT", 
    "API3USDT", 
    "PAXGUSDT", 
    "KDAUSDT", 
    "APEUSDT", 
    "GMTUSDT", 
    "OGNUSDT", 
    "CTSIUSDT", 
    "ARPAUSDT", 
    "ALPHAUSDT", 
    "ZRXUSDT", 
    "GLMRUSDT", 
    "SCRTUSDT", 
    "BAKEUSDT", 
    "ASTRUSDT", 
    "FXSUSDT", 
    "MINAUSDT", 
    "BOBAUSDT", 
    # "1000XECUSDT", -> not supported by exchanges 3.7.2025 
    "ACHUSDT", 
    "BALUSDT", 
    "MTLUSDT", 
    "CVXUSDT", 
    "XCNUSDT", 
    "FLMUSDT", 
    "CTCUSDT", 
    # "LUNA2USDT", -> not supported by exchanges 3.7.2025  
    "OPUSDT", 
    "ONTUSDT", 
    "TRBUSDT", 
    "BELUSDT", 
    "USDCUSDT", 
    "LDOUSDT", 
    "INJUSDT", 
    "STGUSDT", 
    # "1000LUNCUSDT", -> not supported by exchanges 3.7.2025 
    "ETHWUSDT", 
    "GMXUSDT", 
    "APTUSDT", 
    "TWTUSDT", 
    "MAGICUSDT", 
    # "1000BONKUSDT", -> not supported by exchanges 3.7.2025  
    "HIGHUSDT", 
    # "COREUSDT", -> not supported by exchanges 3.7.2025 
    "BLURUSDT", 
    "CFXUSDT", 
    # "1000FLOKIUSDT", -> not supported by exchanges 3.7.2025  
    "SSVUSDT", 
    "RPLUSDT", 
    "TUSDT", 
    "TRUUSDT", 
    "LQTYUSDT", 
    "HFTUSDT", 
    "RLCUSDT", 
    "ARBUSDT", 
    "IDUSDT", 
    "JOEUSDT", 
    "SUIUSDT", 
    # "1000PEPEUSDT", -> not supported by exchanges 3.7.2025 
    "EDUUSDT", 
    "ORDIUSDT", 
    # "10000LADYSUSDT", -> not supported by exchanges 3.7.2025 
    "PHBUSDT", 
    "RADUSDT", 
    "UMAUSDT", 
    "TONUSDT", 
    "MBOXUSDT", 
    "VRUSDT", 
    "MAVUSDT", 
    "MDTUSDT", 
    "XVGUSDT", 
    "PENDLEUSDT", 
    "WLDUSDT", 
    "ARKMUSDT", 
    "AUCTIONUSDT", 
    "FORTHUSDT", 
    "ARKUSDT", 
    "KASUSDT", 
    "BNTUSDT", 
    "GLMUSDT", 
    "CYBERUSDT", 
    "SEIUSDT", 
    "HIFIUSDT", 
    "OGUSDT", 
    "NMRUSDT", 
    "PROMUSDT", 
    "PERPUSDT", 
    "XVSUSDT", 
    "MNTUSDT", 
    "ORBSUSDT", 
    "WAXPUSDT", 
    "BIGTIMEUSDT", 
    "GASUSDT", 
    "POLYXUSDT", 
    "POWRUSDT", 
    "STEEMUSDT", 
    "TIAUSDT", 
    "SNTUSDT", 
    "MEMEUSDT", 
    "CAKEUSDT", 
    "TOKENUSDT", 
    "BEAMUSDT", 
    # "10000SATSUSDT", -> not supported by exchanges 3.7.2025 
    "AERGOUSDT", 
    "AGIUSDT", 
    "PYTHUSDT", 
    "GODSUSDT", 
    # "1000RATSUSDT", -> not supported by exchanges 3.7.2025 
    "MOVRUSDT", 
    "SUPERUSDT", 
    "USTCUSDT", 
    "RAREUSDT", 
    "ONGUSDT", 
    "AXLUSDT", 
    "JTOUSDT", 
    "ACEUSDT", 
    "METISUSDT", 
    "XAIUSDT", 
    "WIFUSDT", 
    "AIUSDT", 
    "MANTAUSDT", 
    "MYROUSDT", 
    "ONDOUSDT", 
    "ALTUSDT", 
    "TAOUSDT", 
    # "10000WENUSDT", -> not supported by exchanges 3.7.2025 
    "JUPUSDT", 
    "ZETAUSDT", 
    "CETUSUSDT", 
    "DYMUSDT", 
    "MAVIAUSDT", 
    "VTHOUSDT", 
    "PIXELUSDT", 
    "STRKUSDT", 
    "MOBILEUSDT", 
    # "1000TURBOUSDT", -> not supported by exchanges 3.7.2025 
    "PORTALUSDT", 
    "SCAUSDT", 
    "AEVOUSDT", 
    "VANRYUSDT", 
    "BOMEUSDT", 
    "OMUSDT", 
    "SLERFUSDT", 
    "ETHFIUSDT", 
    "ZKUSDT", 
    "POPCATUSDT", 
    "ORCAUSDT", 
    "DEGENUSDT", 
    "ENAUSDT", 
    "WUSDT", 
    "TNSRUSDT", 
    "SAGAUSDT", 
    "ZBCNUSDT", 
    "OMNIUSDT", 
    "MERLUSDT", 
    "MEWUSDT", 
    "MELANIAUSDT", 
    "BRETTUSDT", 
    "SAFEUSDT", 
    "REZUSDT", 
    "BBUSDT", 
    "VELOUSDT", 
    "NOTUSDT", 
    # "1000000MOGUSDT", -> not supported by exchanges 3.7.2025 
    "DRIFTUSDT", 
    "PHAUSDT", 
    # "RAYDIUMUSDT", -> not supported by exchanges 3.7.2025 
    "GRIFFAINUSDT", 
    # "DOGUSDT", -> not supported by exchanges 3.7.2025 
    "TRUMPUSDT", 
    "PONKEUSDT", 
    "TAIKOUSDT", 
    # "1000000BABYDOGEUSDT", -> not supported by exchanges 3.7.2025 
    "IOUSDT", 
    "ATHUSDT", 
    "LISTAUSDT", 
    "ZROUSDT", 
    "AEROUSDT", 
    "AKTUSDT", 
    "AIXBTUSDT", 
    # "10000QUBICUSDT", -> not supported by exchanges 3.7.2025 
    "HIVEUSDT", 
    "BIOUSDT", 
    "MOCAUSDT", 
    "PRCLUSDT", 
    "ZEREBROUSDT", 
    "UXLINKUSDT", 
    "A8USDT", 
    "BANANAUSDT", 
    "ARCUSDT", 
    "AVAILUSDT", 
    "DEXEUSDT", 
    "GUSDT", 
    "RENDERUSDT", 
    "AI16ZUSDT", 
    "CGPTUSDT", 
    "SWARMSUSDT", 
    "EIGENUSDT", 
    # "NEIROETHUSDT", -> not supported by exchanges 3.7.2025 
    "DOGSUSDT", 
    "SYNUSDT", 
    "SUNDOGUSDT", 
    "SLFUSDT", 
    "CHESSUSDT", 
    "POLUSDT", 
    "AVAAIUSDT", 
    "KMNOUSDT", 
    "PRIMEUSDT", 
    "FLUXUSDT", 
    "CATIUSDT", 
    "HMSTRUSDT", 
    "1000CATUSDT", 
    # "REXUSDT", -> not supported by exchanges 3.7.2025 
    # "ALEOUSDT", -> not supported by exchanges 3.7.2025 
    # "1000NEIROCTOUSDT", -> not supported by exchanges 3.7.2025 
    "FBUSDT", 
    "COOKIEUSDT", 
    "FIDAUSDT", 
    "MOODENGUSDT", 
    "ALCHUSDT", 
    "SOLVUSDT", 
    "GRASSUSDT", 
    "ACTUSDT", 
    "SCRUSDT", 
    "PUFFERUSDT", 
    "CARVUSDT", 
    "SPXUSDT", 
    "DEEPUSDT", 
    "GOATUSDT", 
    "ALUUSDT", 
    "LUMIAUSDT", 
    # "1000XUSDT", -> not supported by exchanges 3.7.2025 
    "TAIUSDT", 
    "VIRTUALUSDT", 
    "KAIAUSDT", 
    "SWELLUSDT", 
    "PNUTUSDT", 
    "COWUSDT", 
    "HYPEUSDT", 
    "MAJORUSDT", 
    "FARTCOINUSDT", 
    "BANUSDT", 
    "USUALUSDT", 
    "FLOCKUSDT", 
    "SUSDT", 
    "MORPHOUSDT", 
    "OLUSDT", 
    "CHILLGUYUSDT", 
    "ZRCUSDT", 
    "MEUSDT", 
    # "1000000CHEEMSUSDT", -> not supported by exchanges 3.7.2025 
    "COOKUSDT", 
    "THEUSDT", 
    "PENGUUSDT", 
    "SOLOUSDT", 
    # "1000TOSHIUSDT", -> not supported by exchanges 3.7.2025 
    "MOVEUSDT", 
    "XIONUSDT", 
    "ACXUSDT", 
    "GIGAUSDT", 
    "KOMAUSDT", 
    "VELODROMEUSDT", 
    "VANAUSDT", 
    "PLUMEUSDT", 
    "ANIMEUSDT", 
    "VINEUSDT", 
    # "10000ELONUSDT", -> not supported by exchanges 3.7.2025 
    "VVVUSDT", 
    "JELLYJELLYUSDT", 
    "BERAUSDT", 
    "IPUSDT", 
    "TSTBSCUSDT", 
    "XDCUSDT", 
    "SOLAYERUSDT", 
    "B3USDT", 
    "SHELLUSDT", 
    "KAITOUSDT", 
    "GPSUSDT", 
    "AVLUSDT", 
    "REDUSDT", 
    "XTERUSDT", 
    "NILUSDT", 
    "ROAMUSDT", 
    "SERAPHUSDT", 
    "BMTUSDT", 
    "FORMUSDT", 
    "MUBARAKUSDT", 
    "TUTUSDT", 
    "SIRENUSDT", 
    "PARTIUSDT", 
    "WALUSDT", 
    "BANANAS31USDT", 
    "GUNUSDT", 
    "BABYUSDT", 
    "XAUTUSDT", 
    "MLNUSDT", 
    "INITUSDT", 
    "KERNELUSDT", 
    "WCTUSDT", 
    # "BANKUSDT", -> not supported by exchanges 3.7.2025 
    "EPTUSDT", 
    "HYPERUSDT", 
    "OBTUSDT", 
    "SIGNUSDT", 
    "PUNDIXUSDT", 
    "SXTUSDT", 
    "OBOLUSDT", 
    # "SKYAIUSDT", -> not supported by exchanges 3.7.2025 
    "SYRUPUSDT", 
    "SOONUSDT", 
    # "BUSDT", -> not supported by exchanges 3.7.2025 
    "HUMAUSDT", 
    "AUSDT", 
    "SOPHUSDT", 
    "LAUSDT", 
    "SQDUSDT", 
    "SPKUSDT", 
    "SAHARAUSDT"
]

